

CREATE PROCEDURE [AUTH].[ADD_APP_USER]
	@APP_ID VARCHAR(100),
	@PASSWORD_SALT VARCHAR(50) = 'NONE',
	@PASSWORD_HASH VARCHAR(50) = '',
	@FIRST_NAME NVARCHAR(100),
	@LAST_NAME NVARCHAR(100),
	@NAME_ALIAS NVARCHAR(200) = '',
	@PHONE_NUMBER VARCHAR(50),
	@PROFILE_PICTURE VARCHAR(500),
	@IDENTITY_PROVIDER VARCHAR(100),
	@USERNAME VARCHAR(200),
	@USERNAME_ALIAS VARCHAR(200) = '',
	@LANGUAGE_CODE VARCHAR(10) = 'en',
	@IS_ENABLED CHAR(1) = 'Y',
	@EDIT_BY VARCHAR(100)
AS BEGIN

	DECLARE @UID VARCHAR(100) = ((format(getdate(),'yyyyMMddHHmmss')+'_')+CONVERT([nvarchar](50),newid()));

	print 'Creating app user account...';
	INSERT INTO AUTH.TB_APP_USER
	SELECT 
		@UID AS USERID, 
		@PASSWORD_SALT AS PASSWORD_SALT, 
		@PASSWORD_HASH AS PASSWORD_HASH, 
		@FIRST_NAME AS FIRST_NAME, 
		@LAST_NAME AS LAST_NAME, 
		(CASE ISNULL(@NAME_ALIAS, '') WHEN '' THEN @FIRST_NAME + ' ' + @LAST_NAME ELSE @NAME_ALIAS END) AS NAME_ALIAS,
		@PHONE_NUMBER AS PHONE_NUMBER,
		@PROFILE_PICTURE AS PROFILE_PICTURE,
		'New user, created on ' + format(getdate(),'yyyyMMdd') + '.' AS NOTES,
		@IS_ENABLED AS IS_ENABLED,
		NULL AS LAST_LOGIN_TIME,
		GETDATE() AS CREATED_TIME,
		@EDIT_BY AS EDIT_BY,
		GETDATE() AS EDIT_TIME;


	DECLARE @CloudSharpProvider VARCHAR(100) = (
		SELECT TOP 1 CONTROL_VALUE FROM APPLICATIONS.TB_APP_DATA_CONTROL with (nolock) 
		WHERE APP_ID = 'CloudSharpSystemsWeb' AND CONTROL_NAME = 'IDENTITY_PROVIDER' AND CONTROL_TYPE = 'PROVIDER_NAME' AND IS_ENABLED = 'Y'
	);
	IF ISNULL(@CloudSharpProvider, '') = '' THROW 51000, 'CloudSharp Identity Provider not found in DB! Check APPLICATIONS.TB_APP_DATA_CONTROL for Identity Provider name config.', 1;


	print 'Creating CloudSharp Identity...';
	INSERT INTO AUTH.TB_APP_USER_IDENTITY
	SELECT 
		@CloudSharpProvider AS IDENTITY_PROVIDER,
		@USERNAME AS USERNAME,
		@UID AS USERID,
		(CASE ISNULL(@USERNAME_ALIAS, '') WHEN '' THEN @USERNAME ELSE @USERNAME_ALIAS END) AS USERNAME_ALIAS,
		@LANGUAGE_CODE AS LANGUAGE_CODE,
		@IS_ENABLED AS IS_ENABLED,
		@EDIT_BY AS EDIT_BY,
		GETDATE() AS EDIT_TIME;

	IF @IDENTITY_PROVIDER <> @CloudSharpProvider BEGIN
		print 'Creating ' + @IDENTITY_PROVIDER + ' Identity...';
		INSERT INTO AUTH.TB_APP_USER_IDENTITY
		SELECT 
			@IDENTITY_PROVIDER AS IDENTITY_PROVIDER,
			@USERNAME AS USERNAME,
			@UID AS USERID,
			(CASE ISNULL(@USERNAME_ALIAS, '') WHEN '' THEN @USERNAME ELSE @USERNAME_ALIAS END) AS USERNAME_ALIAS,
			@LANGUAGE_CODE AS LANGUAGE_CODE,
			@IS_ENABLED AS IS_ENABLED,
			@EDIT_BY AS EDIT_BY,
			GETDATE() AS EDIT_TIME;
	END;


	DECLARE @LOG_ID VARCHAR(100) = ((format(getdate(),'yyyyMMddHHmmss')+'_')+CONVERT([nvarchar](50),newid()));
	INSERT INTO APPLICATIONS.TB_CENTRAL_SYSTEM_LOG
	SELECT 
		@LOG_ID AS LOG_ID,
		@APP_ID AS APP_ID,
		ISNULL(HOST_NAME(), 'Unknown') AS SYSTEM_NAME,
		CONVERT(VARCHAR(100), CURRENT_TRANSACTION_ID()) AS TRACE_ID,
		'GOOD' AS RECORD_TYPE,
		@UID AS RECORD_KEY,
		'Account enabled: ' + @IS_ENABLED AS RECORD_VALUE1,
		'User full name: ' + @FIRST_NAME + ' ' + @LAST_NAME AS RECORD_VALUE2,
		'Identity 1: ' + @CloudSharpProvider + '/' + @USERNAME AS RECORD_VALUE3,
		'Identity 2: ' + @IDENTITY_PROVIDER + '/' + @USERNAME AS RECORD_VALLUE4,
		'Account added by: ' + @EDIT_BY AS RECORD_VALUE5,
		'SQL Transaction; Create new app user with identity;' AS RECORD_MESSAGE,
		'' AS RECORD_NOTE,
		@EDIT_BY AS EDIT_BY,
		GETDATE() AS EDIT_TIME;

END;