
CREATE FUNCTION [AUTH].[GET_APP_IDENTITY_USER_PROFILE_HEADERS_BY_TEAM](@IDENTITY_PROVIDER VARCHAR(100), @TEAM_ID VARCHAR(100))
RETURNS TABLE AS RETURN
	WITH TEAM_USER AS (
		SELECT UT.* FROM AUTH.TB_APP_USER_TEAM UT WHERE UT.TEAM_ID = @TEAM_ID AND UT.IS_ENABLED = 'Y'
	),
	USER_PROFILE AS (
		SELECT FIRST_NAME, LAST_NAME, NAME_ALIAS, PHONE_NUMBER, PROFILE_PICTURE, NOTES, IDENTITY_PROVIDER, USERNAME_ALIAS, LANGUAGE_CODE
		FROM TEAM_USER
		INNER JOIN AUTH.TB_APP_USER_IDENTITY I ON TEAM_USER.USERID = I.USERID AND I.IS_ENABLED = 'Y'
		INNER JOIN AUTH.TB_APP_USER U ON U.USERID = I.USERID AND U.IS_ENABLED = 'Y'
	),
	IDENTITY_PROFILE AS (
		SELECT * FROM USER_PROFILE WHERE IDENTITY_PROVIDER = @IDENTITY_PROVIDER
	)
	SELECT * FROM IDENTITY_PROFILE
	UNION ALL
	SELECT * FROM USER_PROFILE WHERE 
		IDENTITY_PROVIDER = (
			SELECT TOP 1 CONTROL_VALUE FROM APPLICATIONS.TB_APP_DATA_CONTROL with (nolock) 
			WHERE APP_ID = 'CloudSharpSystemsWeb' AND CONTROL_NAME = 'IDENTITY_PROVIDER' AND CONTROL_TYPE = 'PROVIDER_NAME' AND IS_ENABLED = 'Y'
		)
		AND USERNAME_ALIAS NOT IN (
			SELECT USERNAME_ALIAS FROM IDENTITY_PROFILE
		)
	;