
CREATE FUNCTION [AUTH].[GET_APP_IDENTITY_USER_PROFILE_HEADER](@IDENTITY_PROVIDER VARCHAR(100), @USERID VARCHAR(100))
RETURNS TABLE AS RETURN
	--DECLARE @IDENTITY_PROVIDER VARCHAR(100) = 'GOOGLE';
	--DECLARE @USERID VARCHAR(100) = '20240511173746_8374F1CA-6640-454E-8E8F-192FAACA8B32';
	WITH USER_IDENTITY AS (
		SELECT * FROM AUTH.TB_APP_USER_IDENTITY 
		WHERE IDENTITY_PROVIDER = @IDENTITY_PROVIDER AND [USERID] = @USERID AND IS_ENABLED = 'Y'
	)
	SELECT FIRST_NAME, LAST_NAME, NAME_ALIAS, PHONE_NUMBER, PROFILE_PICTURE, NOTES, IDENTITY_PROVIDER, USERNAME_ALIAS, LANGUAGE_CODE
	FROM AUTH.TB_APP_USER U INNER JOIN USER_IDENTITY I ON U.USERID = I.USERID;