
CREATE FUNCTION AUTH.GET_TEAMS_BY_USER(@APP_ID VARCHAR(100), @USERID VARCHAR(100), @WITH_DEFAULT_ACCOUNT CHAR(1))
RETURNS TABLE AS RETURN
	--DECLARE @USERID AS VARCHAR(100) = '20240511173746_8374F1CA-6640-454E-8E8F-192FAACA8B32';
	--DECLARE @WITH_DEFAULT_ACCOUNT AS CHAR(1) = 'Y';
	SELECT * FROM AUTH.TB_APP_TEAM
	WHERE APP_ID = @APP_ID AND TEAM_ID IN (
		SELECT TEAM_ID FROM AUTH.TB_APP_USER_TEAM 
		WHERE USERID = @USERID AND IS_ENABLED = 'Y'
	) AND IS_ENABLED = 'Y'
	UNION
	SELECT * FROM AUTH.TB_APP_TEAM
	WHERE APP_ID = @APP_ID AND TEAM_NAME = 'My Notes' AND IS_ENABLED = 'Y' AND @WITH_DEFAULT_ACCOUNT = 'Y';