CREATE TABLE [AUTH].[TB_APP_USER] (
    [USERID]          VARCHAR (100)  DEFAULT ((format(getdate(),'yyyyMMddHHmmss')+'_')+CONVERT([nvarchar](50),newid())) NOT NULL,
    [PASSWORD_SALT]   VARCHAR (50)   NOT NULL,
    [PASSWORD_HASH]   VARCHAR (50)   NOT NULL,
    [FIRST_NAME]      NVARCHAR (100) NOT NULL,
    [LAST_NAME]       NVARCHAR (100) NOT NULL,
    [NAME_ALIAS]      NVARCHAR (100) NOT NULL,
    [PHONE_NUMBER]    VARCHAR (50)   NOT NULL,
    [PROFILE_PICTURE] VARCHAR (500)  NOT NULL,
    [NOTES]           VARCHAR (500)  NOT NULL,
    [IS_ENABLED]      CHAR (1)       NOT NULL,
    [LAST_LOGIN_TIME] DATETIME       NULL,
    [CREATED_TIME]    DATETIME       DEFAULT (getdate()) NOT NULL,
    [EDIT_BY]         VARCHAR (100)  NOT NULL,
    [EDIT_TIME]       DATETIME       DEFAULT (getdate()) NOT NULL,
    PRIMARY KEY CLUSTERED ([USERID] ASC),
    CHECK ([IS_ENABLED]='N' OR [IS_ENABLED]='Y')
);

