CREATE FUNCTION [APPLICATIONS].[CENTRAL_SYSTEM_LOG_VOLUME](@DateOffSet AS INT, @AppID AS VARCHAR(100)) 
RETURNS TABLE AS RETURN
	WITH ListDates(AllDates) AS 
	(   SELECT DATEADD(DAY, -@DateOffSet, GETDATE()) AS [DATE]
		UNION ALL
		SELECT DATEADD(DAY, 1, AllDates)
		FROM ListDates 
		WHERE AllDates < GETDATE())
	SELECT @AppID AS [APP_ID], [DATE], SUM([COUNT]) AS [COUNT] FROM (
		SELECT CONVERT(DATE, EDIT_TIME) AS [DATE], COUNT(1) AS [COUNT]
		FROM APPLICATIONS.TB_CENTRAL_SYSTEM_LOG with (nolock)
		WHERE APP_ID = @AppID AND EDIT_TIME > DATEADD(DAY, -@DateOffSet, GETDATE())
		GROUP BY CONVERT(DATE, EDIT_TIME)

		UNION ALL

		SELECT CONVERT(DATE, AllDates) AS [DATE], 0 AS [COUNT]
		FROM ListDates
	) AGG
	GROUP BY [DATE]
	--ORDER BY [DATE]
	;
