



CREATE PROCEDURE [NETWORK].[LOAD_BALANCE_LEAST_CONNECTIONS] 
	@SITE_ID AS VARCHAR(100),
	@CLIENT_IP AS VARCHAR(20),
	@CLIENT_THREAD_ID AS VARCHAR(100),
	@RESOURCE_SIZE AS INT,
	@HOST_IP AS VARCHAR(100) OUTPUT,
	@RESOURCE_UNIT INT OUTPUT
	-- Created by Shu-Yuan Yang 09/20/2023
AS
BEGIN

	SET @HOST_IP = NULL;


	DECLARE @app_ID VARCHAR(50) = 'CloudSharpSystemsWeb';
	DECLARE @data_control_name VARCHAR(50) = 'LOAD_BALANCING_ALGORITHM';
	DECLARE @algorithm_type VARCHAR(50) = 'LEAST_CONNECTIONS';
	
	DECLARE @load_cache_str VARCHAR(50) = 'LOAD_CACHE_';
	DECLARE @max_cache_load INT = 1000;
	
	EXEC NETWORK.LOAD_BALANCE_VALIDATE_LOAD_CACHE @SITE_ID, @max_cache_load;
	
	/*
	UPDATE APPLICATIONS.TB_APP_DATA_CONTROL SET IS_ENABLED = 'Y', EDIT_BY = @app_ID, EDIT_DATE = GETDATE()
	WHERE APP_ID = @app_ID AND CONTROL_NAME = @data_control_name AND CONTROL_TYPE = @algorithm_type AND CONTROL_LEVEL IN (
		SELECT @load_cache_str + HOST_IP FROM NETWORK.TB_WEBSITE_HOST
		WHERE SITE_ID = @SITE_ID AND STATUS = 'NORMAL'
	)

	UPDATE APPLICATIONS.TB_APP_DATA_CONTROL SET IS_ENABLED = 'N', EDIT_BY = @app_ID, EDIT_DATE = GETDATE()
	WHERE APP_ID = @app_ID AND CONTROL_NAME = @data_control_name AND CONTROL_TYPE = @algorithm_type AND CONTROL_LEVEL IN (
		SELECT @load_cache_str + HOST_IP FROM NETWORK.TB_WEBSITE_HOST
		WHERE SITE_ID = @SITE_ID AND STATUS <> 'NORMAL'
	)
	*/

	SELECT TOP 1 @HOST_IP = RIGHT(CONTROL_LEVEL, LEN(CONTROL_LEVEL) - LEN(@load_cache_str)) FROM APPLICATIONS.TB_APP_DATA_CONTROL
	WHERE APP_ID = @app_ID AND CONTROL_NAME = @data_control_name AND CONTROL_TYPE = @algorithm_type 
	AND CONTROL_LEVEL IN (
		SELECT @load_cache_str + HOST_IP FROM NETWORK.GET_SERVER_LOAD(@SITE_ID) 
		WHERE [NETWORK].[IS_HOST_RESPONSIVE](SERVER_STATUS, IP_STATUS) = 'Y' -- Shu-Yuan Yang 11142023 modified to use function to determine responsive status
		AND NET_LOAD_CAPACITY - RESOURCE_LOAD > @RESOURCE_SIZE
	)
	ORDER BY CONVERT(FLOAT, CONTROL_VALUE) ASC;

	UPDATE APPLICATIONS.TB_APP_DATA_CONTROL SET CONTROL_VALUE = CONVERT(VARCHAR(250), CONVERT(FLOAT, CONTROL_VALUE) + @RESOURCE_SIZE), IS_ENABLED = 'Y', EDIT_BY = @app_ID, EDIT_DATE = GETDATE()
	WHERE APP_ID = @app_ID AND CONTROL_NAME = @data_control_name AND CONTROL_TYPE = @algorithm_type AND CONTROL_LEVEL = @load_cache_str + @HOST_IP;

	/*
	SELECT TOP 1 @HOST_IP = HOST_IP FROM NETWORK.GET_SERVER_LOAD(@SITE_ID) 
	WHERE SERVER_STATUS = 'RUNNING' AND IP_STATUS = 'NORMAL' AND NET_LOAD_CAPACITY - RESOURCE_LOAD > @RESOURCE_SIZE
	ORDER BY RESOURCE_LOAD ASC;
	*/

	IF @HOST_IP IS NULL SET @RESOURCE_UNIT = -1;
	ELSE				SET @RESOURCE_UNIT = 1;


END;
