



CREATE PROCEDURE [NETWORK].[LOAD_BALANCE] 
	@SITE_ID AS VARCHAR(100),
	@CLIENT_IP AS VARCHAR(20),
	@CLIENT_THREAD_ID AS VARCHAR(100),
	@RESOURCE_SIZE AS INT,
	@HOST_IP AS VARCHAR(100) OUTPUT,
	@RESOURCE_UNIT INT OUTPUT
	-- Created by Shu-Yuan Yang 10/13/2023
AS
BEGIN
	-- 0. Clear out abnormal sessions:
	EXEC NETWORK.VALIDATE_USER_SESSIONS @SITE_ID;


	-- 1. If client already has a connected session on a normally functioning host IP, return that host IP:
	SELECT TOP 1 @HOST_IP = TB_H.HOST_IP FROM NETWORK.TB_WEBSITE_HOST TB_H
	WHERE TB_H.SITE_ID = @SITE_ID 
	AND [NETWORK].[IS_HOST_RESPONSIVE]('RUNNING', TB_H.STATUS) = 'Y' -- Shu-Yuan Yang 11142023 modified to use function to determine responsive status
	AND TB_H.HOST_IP IN (
		SELECT TB_S.HOST_IP FROM NETWORK.TB_USER_SESSION TB_S 
		WHERE TB_S.CLIENT_IP = @CLIENT_IP AND 
			  TB_S.THREAD_ID = @CLIENT_THREAD_ID AND
			  TB_S.IS_VALID = 'Y'
	);
	IF @HOST_IP IS NOT NULL BEGIN
		SET @RESOURCE_UNIT = -1;
		RETURN;
	END
	
	-- 3. Determine Load Balancing Algorithms to use:
	DECLARE @ALGORITHM VARCHAR(150) = NULL;
	SELECT @ALGORITHM = LOAD_BALANCING_ALGORITHM FROM NETWORK.TB_WEBSITE S
	WHERE S.SITE_ID = @SITE_ID AND IS_ENABLED = 'Y';

	-- 4. Execute the load balancing algorithm:
	IF @ALGORITHM = 'WEIGHTED_ROUND_ROBIN' BEGIN
		EXEC NETWORK.LOAD_BALANCE_WEIGHTED_ROUND_ROBIN @SITE_ID, @CLIENT_IP, @CLIENT_THREAD_ID, @RESOURCE_SIZE, @HOST_IP OUTPUT, @RESOURCE_UNIT OUTPUT;
	
	END ELSE IF @ALGORITHM = 'LEAST_CONNECTIONS' BEGIN
		EXEC NETWORK.LOAD_BALANCE_LEAST_CONNECTIONS    @SITE_ID, @CLIENT_IP, @CLIENT_THREAD_ID, @RESOURCE_SIZE, @HOST_IP OUTPUT, @RESOURCE_UNIT OUTPUT;
	
	END ELSE IF @ALGORITHM = 'GEOLOCATION_GLOBAL' BEGIN
		SET @RESOURCE_UNIT = 1;

	END ELSE IF @ALGORITHM = 'WEIGHTED_FAULT_AVOIDANCE' BEGIN
		EXEC NETWORK.LOAD_BALANCE_WEIGHTED_FAULT_AVOIDANCE    @SITE_ID, @CLIENT_IP, @CLIENT_THREAD_ID, @RESOURCE_SIZE, @HOST_IP OUTPUT, @RESOURCE_UNIT OUTPUT;
	
	END ELSE BEGIN
		SET @ALGORITHM = 'NONE';
		EXEC NETWORK.LOAD_BALANCE_NONE				   @SITE_ID, @CLIENT_IP, @CLIENT_THREAD_ID, @RESOURCE_SIZE, @HOST_IP OUTPUT, @RESOURCE_UNIT OUTPUT;
	
	END


	-- Shu-Yuan Yang 10/23/2023 added to debug empty resource unit:
	IF @HOST_IP IS NULL SET @RESOURCE_UNIT = -1;

	PRINT @ALGORITHM; -- debug

END;
