




CREATE PROCEDURE [NETWORK].[LOAD_BALANCE_VALIDATE_LOAD_CACHE]
	@SITE_ID VARCHAR(100),
	@MAX_CACHE_LOAD INT,
	@IS_RESET CHAR(1) = 'N'
AS
BEGIN
	-- DECLARE @SITE_ID VARCHAR(100) = 'CS_SHUYUAN_LOCAL_TEST_PAGE';
	
	DECLARE @app_ID VARCHAR(50) = 'CloudSharpSystemsWeb';
	DECLARE @data_control_name VARCHAR(50) = 'LOAD_BALANCING_ALGORITHM';
	DECLARE @algorithm_type VARCHAR(50) = (SELECT TOP 1 LOAD_BALANCING_ALGORITHM FROM NETWORK.TB_WEBSITE with (nolock) WHERE SITE_ID = @SITE_ID);
	DECLARE @load_cache_str VARCHAR(50) = 'LOAD_CACHE_';
	
	DECLARE @invalidation_timout FLOAT = 0;

	SELECT @invalidation_timout = CONVERT(FLOAT, CONTROL_VALUE) FROM APPLICATIONS.V_APP_DATA_CONTROL
	WHERE APP_ID = @app_ID AND CONTROL_NAME = @data_control_name AND CONTROL_TYPE = @algorithm_type
	AND CONTROL_LEVEL = 'INVALIDATION_TIMEOUT'
	AND IS_APP_ENABLED = 'Y' AND IS_CONTROL_ENABLED = 'Y';
	
	Print @invalidation_timout;
	
	-- Invalidate if too old:
	--SELECT * FROM APPLICATIONS.TB_APP_DATA_CONTROL
	UPDATE APPLICATIONS.TB_APP_DATA_CONTROL SET CONTROL_VALUE = '0', IS_ENABLED = 'N', EDIT_BY = @app_ID, EDIT_DATE = GETDATE()
	WHERE APP_ID = @app_ID AND CONTROL_NAME = @data_control_name AND CONTROL_TYPE = @algorithm_type
	AND CONTROL_LEVEL LIKE @load_cache_str + '%' AND CONTROL_LEVEL IN (
		SELECT @load_cache_str + HOST_IP FROM NETWORK.TB_WEBSITE_HOST WHERE SITE_ID = @SITE_ID
	)
	AND IS_ENABLED = 'Y'
	AND (@IS_RESET = 'Y' OR EDIT_DATE < DATEADD(HOUR, -@invalidation_timout, GETDATE()) )
	;


	-- Reduce load number if load cache is too large:
	IF EXISTS(
		SELECT TOP 1 1 FROM APPLICATIONS.TB_APP_DATA_CONTROL
		WHERE APP_ID = @app_ID AND CONTROL_NAME = @data_control_name AND CONTROL_TYPE = @algorithm_type
		AND CONTROL_LEVEL LIKE @load_cache_str + '%' AND CONTROL_LEVEL IN (
			SELECT @load_cache_str + HOST_IP FROM NETWORK.TB_WEBSITE_HOST WHERE SITE_ID = @SITE_ID
		)
		AND IS_ENABLED = 'Y'
		AND CONVERT(FLOAT, CONTROL_VALUE) > @MAX_CACHE_LOAD
	)
	BEGIN
		UPDATE APPLICATIONS.TB_APP_DATA_CONTROL SET CONTROL_VALUE = CONVERT(VARCHAR(250), CONVERT(FLOAT, CONTROL_VALUE) - @MAX_CACHE_LOAD), EDIT_BY = @app_ID, EDIT_DATE = GETDATE()
		WHERE APP_ID = @app_ID AND CONTROL_NAME = @data_control_name AND CONTROL_TYPE = @algorithm_type
		AND CONTROL_LEVEL LIKE @load_cache_str + '%' AND CONTROL_LEVEL IN (
			SELECT @load_cache_str + HOST_IP FROM NETWORK.TB_WEBSITE_HOST WHERE SITE_ID = @SITE_ID
		)
		AND IS_ENABLED = 'Y';
	END

	
	-- Add new active hosts to cache:
	INSERT INTO APPLICATIONS.TB_APP_DATA_CONTROL
	SELECT @app_ID, @data_control_name, @algorithm_type, @load_cache_str + HOST_IP, '0', 'Cached load for application host ' + HOST_IP, 'Y', @app_ID, GETDATE()
	FROM NETWORK.TB_WEBSITE_HOST
	WHERE SITE_ID = @SITE_ID 
	AND [NETWORK].[IS_HOST_RESPONSIVE]('RUNNING', [STATUS]) = 'Y' -- Shu-Yuan Yang 11142023 modified to use function to determine responsive status
	AND HOST_IP NOT IN (
		SELECT RIGHT(CONTROL_LEVEL, LEN(CONTROL_LEVEL) - LEN(@load_cache_str)) FROM APPLICATIONS.V_APP_DATA_CONTROL 
		WHERE APP_ID = @app_ID AND CONTROL_NAME = @data_control_name AND CONTROL_TYPE = @algorithm_type
		AND CONTROL_LEVEL LIKE @load_cache_str + '%'
		AND IS_APP_ENABLED = 'Y'
	);
	

	
END;
