





CREATE PROCEDURE [NETWORK].[LOAD_BALANCE_NONE] 
	@SITE_ID AS VARCHAR(100),
	@CLIENT_IP AS VARCHAR(20),
	@CLIENT_THREAD_ID AS VARCHAR(100),
	@RESOURCE_SIZE AS INT,
	@HOST_IP AS VARCHAR(100) OUTPUT,
	@RESOURCE_UNIT INT OUTPUT
	-- Created by Shu-Yuan Yang 10/13/2023
AS
BEGIN
	
	SET @HOST_IP = NULL;

	SELECT TOP 1 @HOST_IP = HOST_IP FROM NETWORK.GET_SERVER_LOAD(@SITE_ID) 
	WHERE [NETWORK].[IS_HOST_RESPONSIVE](SERVER_STATUS, IP_STATUS) = 'Y'; -- Shu-Yuan Yang 11142023 modified to use function to determine responsive status

	IF @HOST_IP IS NULL SET @RESOURCE_UNIT = -1;
	ELSE				SET @RESOURCE_UNIT = 1;


END;
