




CREATE PROCEDURE [NETWORK].[LOAD_BALANCE_RESET]
	@SITE_ID VARCHAR(150),
	@ALGORITHM VARCHAR(150),
	@MAX_SEARCH_COUNT INT,
	@EDIT_BY VARCHAR(150)
AS
BEGIN
	DECLARE @OLD_ALGORITHM VARCHAR(150) = NULL;
	SELECT @OLD_ALGORITHM = LOAD_BALANCING_ALGORITHM FROM NETWORK.TB_WEBSITE WHERE SITE_ID = @SITE_ID;
	IF @OLD_ALGORITHM IS NULL SET @OLD_ALGORITHM = 'NONE';

	SET @ALGORITHM = UPPER(@ALGORITHM);

	-- 0. Reset Max Search Count (not implemented):

	-- 1. Reset load balancer cache
	-- Reset Weighted Round Robin Cache:
	IF @OLD_ALGORITHM = 'WEIGHTED_ROUND_ROBIN' BEGIN
		DECLARE @load_capacity INT = 0;
		
		SELECT TOP 1 @load_capacity = NET_LOAD_CAPACITY FROM NETWORK.GET_SERVER_LOAD(@SITE_ID) 
		WHERE [NETWORK].[IS_HOST_RESPONSIVE](SERVER_STATUS, IP_STATUS) = 'Y' -- Shu-Yuan Yang 11142023 modified to use function to determine responsive status
		ORDER BY NET_LOAD_CAPACITY DESC;

		UPDATE APPLICATIONS.TB_APP_DATA_CONTROL SET CONTROL_VALUE = '1', EDIT_BY = @EDIT_BY, EDIT_DATE = GETDATE()
		WHERE APP_ID = 'CloudSharpSystemsWeb' AND CONTROL_NAME = 'LOAD_BALANCING_ALGORITHM' AND CONTROL_TYPE = 'WEIGHTED_ROUND_ROBIN' 
		AND CONTROL_LEVEL = 'CURRENT_INDEX' AND IS_ENABLED = 'Y';
						
		UPDATE APPLICATIONS.TB_APP_DATA_CONTROL SET CONTROL_VALUE = '0', EDIT_BY = @EDIT_BY, EDIT_DATE = GETDATE()
		WHERE APP_ID = 'CloudSharpSystemsWeb' AND CONTROL_NAME = 'LOAD_BALANCING_ALGORITHM' AND CONTROL_TYPE = 'WEIGHTED_ROUND_ROBIN' 
		AND CONTROL_LEVEL = 'CURRENT_LOAD' AND IS_ENABLED = 'Y';

		UPDATE APPLICATIONS.TB_APP_DATA_CONTROL SET CONTROL_VALUE = CONVERT(VARCHAR(250), @load_capacity / 10), EDIT_BY = @EDIT_BY, EDIT_DATE = GETDATE()
		WHERE APP_ID = 'CloudSharpSystemsWeb' AND CONTROL_NAME = 'LOAD_BALANCING_ALGORITHM' AND CONTROL_TYPE = 'WEIGHTED_ROUND_ROBIN' 
		AND CONTROL_LEVEL = 'CURRENT_MAX_WEIGHT' AND IS_ENABLED = 'Y';

	END


	-- Reset Least Connection and Fault Avoidance Cache:
	ELSE IF @OLD_ALGORITHM IN ('LEAST_CONNECTIONS', 'WEIGHTED_FAULT_AVOIDANCE') BEGIN
		DECLARE @max_cache_load INT = 1000;
		EXEC NETWORK.LOAD_BALANCE_VALIDATE_LOAD_CACHE @SITE_ID, @max_cache_load, 'Y';
	END

	
	-- Reset IPV6 Global Cache:
	




	-- 2. Reset load balancing algorithm:
	DECLARE @valid_alg CHAR(1) = 'N';
	IF EXISTS(
		SELECT TOP 1 1 FROM APPLICATIONS.TB_APP_DATA_CONTROL 
		WHERE CONTROL_NAME = 'LOAD_BALANCING_ALGORITHM' AND CONTROL_TYPE = 'ALGORITHM_TYPE' AND CONTROL_VALUE = @ALGORITHM
	) SET @valid_alg = 'Y';
	
	IF @valid_alg <> 'Y'
	BEGIN
		SET @ALGORITHM = 'NONE';
		-- DECLARE @ERRMSG NVARCHAR(MAX) = ISNULL(@ALGORITHM, '') + ' is not a valid implemented load balancing algorithm!';
		-- RAISERROR(@ERRMSG, 16, 1);
	END

	UPDATE NETWORK.TB_WEBSITE SET LOAD_BALANCING_ALGORITHM = @ALGORITHM, EDIT_BY = @EDIT_BY, EDIT_TIME = GETDATE()
	WHERE SITE_ID = @SITE_ID;


END;
