
CREATE PROCEDURE [NETWORK].[RESET_SERVER_CAPACITY] 
--DECLARE
	@HOST_IP VARCHAR(20),
	@CAPACITY INT,
	@EDIT_BY VARCHAR(100),
	@PRESET_ERROR_RATE FLOAT = 0.0
AS
BEGIN
	
	-- SELECT * FROM NETWORK.TB_USER_SESSION
	-- WHERE IS_VALID = 'Y' AND HOST_IP = @HOST_IP;

	INSERT INTO NETWORK.TB_USER_SESSION_HISTORY_LOG
	SELECT TB_S.SESSION_ID, TB_S.CLIENT_IP, TB_S.THREAD_ID, TB_S.HOST_IP, TB_S.RESOURCE_UNIT, TB_S.CLIENT_LOCATION, TB_S.REQUESTED_TIME, TB_S.RESOURCE_SIZE, TB_S.EDIT_BY, TB_S.EDIT_TIME, GETDATE()
	FROM NETWORK.TB_USER_SESSION TB_S WHERE TB_S.HOST_IP = @HOST_IP; 

	--SELECT * FROM NETWORK.TB_USER_SESSION 
	DELETE FROM NETWORK.TB_USER_SESSION 
	WHERE HOST_IP = @HOST_IP;

	UPDATE PRODUCTS.TB_SERVER SET NET_LOAD_CAPACITY = @CAPACITY, EDIT_BY = @EDIT_BY, EDIT_TIME = GETDATE()
	WHERE SERIAL_NO = (SELECT TOP 1 H.SERIAL_NO 
		FROM NETWORK.TB_WEBSITE_HOST H
		WHERE H.HOST_IP = @HOST_IP
	);


	-- Shu-Yuan Yang 11062023 added to record preset error rate (for monitoring purpose):
	UPDATE APPLICATIONS.TB_APP_DATA_CONTROL SET CONTROL_VALUE = CONVERT(VARCHAR(250), @PRESET_ERROR_RATE), EDIT_BY = @EDIT_BY, EDIT_DATE = GETDATE()
	WHERE APP_ID = 'CloudSharpSystemsWeb' AND CONTROL_NAME = 'LOAD_BALANCING_ALGORITHM' AND CONTROL_TYPE = 'WEIGHTED_FAULT_AVOIDANCE' AND CONTROL_LEVEL = '__PRESET_ERROR_RATE_' + @HOST_IP;


END;
