CREATE PROCEDURE [NETWORK].[UPDATE_HOST_STATUS] 
--DECLARE
	@HOST_IP VARCHAR(20),
	@PORT VARCHAR(10),
	@STATUS VARCHAR(20),
	@EDIT_BY VARCHAR(100),
	@TRACE_ID VARCHAR(100) = NULL,	-- Shu-Yuan Yang 11102023 added
	@INPUT_MESSAGE VARCHAR(500) = '',
	@LATENCY FLOAT = 0 -- Shu-Yuan Yang 12162023 added to track monitoring latency as well
AS
BEGIN
	
	UPDATE NETWORK.TB_WEBSITE_HOST SET [STATUS] = @STATUS, EDIT_BY = @EDIT_BY, EDIT_TIME = GETDATE()
	WHERE HOST_IP = @HOST_IP AND [PORT] = @PORT;

	DECLARE @SITE_ID VARCHAR(150) = NULL;
	SELECT @SITE_ID = SITE_ID FROM NETWORK.TB_WEBSITE_HOST
	WHERE HOST_IP = @HOST_IP AND [PORT] = @PORT;

	-- Shu-Yuan Yang 11102023 added
	EXEC NETWORK.INSERT_HOST_STATUS_LOG @HOST_IP, @STATUS, @TRACE_ID, @INPUT_MESSAGE, @EDIT_BY, @LATENCY;

	IF @SITE_ID IS NOT NULL EXEC NETWORK.VALIDATE_USER_SESSIONS @SITE_ID;

END;
