
CREATE PROCEDURE [NETWORK].[UPDATE_HOST_IP_BY_SN] @SN AS VARCHAR(50), @NEW_IP AS VARCHAR(20) AS
BEGIN
	UPDATE NETWORK.TB_WEBSITE_HOST SET HOST_IP = @NEW_IP, EDIT_BY = 'AutoIPRegistrationTask', EDIT_TIME = GETDATE() 
	WHERE UPPER(SERIAL_NO) = UPPER(@SN);
END;
