


CREATE PROCEDURE [NETWORK].[VALIDATE_USER_SESSIONS]
	@SITE_ID AS VARCHAR(100)
	-- Created by Shu-Yuan Yang 09/20/2023
	-- Determine each user session validity by server host status. Invalidate sessions for abnormal host status and clear the session data.
AS
BEGIN
	DECLARE @ProblemHostIP TABLE(HOST_IP VARCHAR(20));

	WITH TB_H AS (SELECT H.* FROM NETWORK.TB_WEBSITE_HOST H WHERE H.SITE_ID = @SITE_ID),
	TB_SER AS (SELECT * FROM PRODUCTS.TB_SERVER S WHERE S.SERIAL_NO IN (SELECT TB_H.SERIAL_NO FROM TB_H)),
	TB_PROBLEM_SER AS (
		SELECT TB_H.SERIAL_NO FROM TB_H WHERE [NETWORK].[IS_HOST_RESPONSIVE]('RUNNING', TB_H.STATUS) = 'N' -- Shu-Yuan Yang 11142023 modified to use function to determine responsive status
		UNION
		SELECT TB_SER.SERIAL_NO FROM TB_SER WHERE [NETWORK].[IS_HOST_RESPONSIVE](TB_SER.STATUS, 'NORMAL') = 'N'
	)
	INSERT INTO @ProblemHostIP 
	SELECT H.HOST_IP FROM NETWORK.TB_WEBSITE_HOST H WHERE H.SERIAL_NO IN (SELECT TB_PROBLEM_SER.SERIAL_NO FROM TB_PROBLEM_SER);

	UPDATE NETWORK.TB_USER_SESSION SET IS_VALID = 'N'
	WHERE HOST_IP IN (SELECT HOST_IP FROM @ProblemHostIP);

	INSERT INTO NETWORK.TB_USER_SESSION_HISTORY_LOG
	SELECT TB_S.SESSION_ID, TB_S.CLIENT_IP, TB_S.THREAD_ID, TB_S.HOST_IP, TB_S.RESOURCE_UNIT, TB_S.CLIENT_LOCATION, TB_S.REQUESTED_TIME, TB_S.RESOURCE_SIZE, TB_S.EDIT_BY, TB_S.EDIT_TIME, GETDATE()
	FROM NETWORK.TB_USER_SESSION TB_S WHERE TB_S.HOST_IP IN (SELECT HOST_IP FROM @ProblemHostIP) AND TB_S.IS_VALID = 'N'; 

	DELETE FROM NETWORK.TB_USER_SESSION
	WHERE HOST_IP IN (SELECT HOST_IP FROM @ProblemHostIP);
END;
