<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Geolocation" Version="1.2.1" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.7.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\APIConnector\APIConnector.csproj" />
    <ProjectReference Include="..\AuxiliaryClassLibrary\AuxiliaryClassLibrary.csproj" />
    <ProjectReference Include="..\CloudSharpSystemsCoreLibrary\CloudSharpSystemsCoreLibrary.csproj" />
    <ProjectReference Include="..\DBConnectionLibrary\DBConnectionLibrary.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Views\access_code_email.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Views\access_code_verification.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>