
CREATE FUNCTION [INTERFACES].[GET_MENU_ITEMS_BY_MENU](@SITE_ID VARCHAR(100), @MENU_NAME VARCHAR(100), @USER_ID VARCHAR(100))
RETURNS TABLE AS RETURN
	WITH MENU_HEADER AS (SELECT * FROM INTERFACES.TB_WEBSITE_MENU_HEADER WHERE SITE_ID = @SITE_ID AND MENU_NAME = @MENU_NAME AND [USER_ID] = @USER_ID AND IS_ENABLED = 'Y')
	SELECT MENU_HEADER.DISPLAY_NAME AS MENU_DISPLAY_NAME, -1 AS MENU_RANKING, ITEM_NAME, MENU_ITEM.DISPLAY_NAME, ROUTE_TYPE, [ROUTE], ICON, RANKING
	FROM MENU_HEADER INNER JOIN INTERFACES.TB_WEBSITE_MENU_ITEM MENU_ITEM
	ON MENU_HEADER.HEADER_ID = MENU_ITEM.HEADER_ID
	WHERE MENU_ITEM.IS_ENABLED = 'Y';