
CREATE FUNCTION [INTERFACES].[GET_SUBMENU_ITEMS_BY_MENU](@SITE_ID VARCHAR(100), @MENU_NAME VARCHAR(100), @USER_ID VARCHAR(100))
RETURNS TABLE AS RETURN
	WITH MAIN_MENU AS (SELECT * FROM INTERFACES.GET_MENU_ITEMS_BY_MENU(@SITE_ID, @MENU_NAME, @USER_ID)),
		 MENU_HEADER AS (SELECT H.HEADER_ID, H.DISPLAY_NAME, MAIN_MENU.RANKING
						 FROM INTERFACES.TB_WEBSITE_MENU_HEADER H INNER JOIN MAIN_MENU
						 ON H.HEADER_ID = MAIN_MENU.[ROUTE]
						 WHERE IS_ENABLED = 'Y')
	SELECT MENU_HEADER.DISPLAY_NAME MENU_DISPLAY_NAME, MENU_HEADER.RANKING AS MENU_RANKING, ITEM_NAME, MENU_ITEM.DISPLAY_NAME, ROUTE_TYPE, [ROUTE], ICON, MENU_ITEM.RANKING 
	FROM MENU_HEADER LEFT JOIN INTERFACES.TB_WEBSITE_MENU_ITEM MENU_ITEM
	ON MENU_HEADER.HEADER_ID = MENU_ITEM.HEADER_ID AND MENU_ITEM.IS_ENABLED = 'Y'
	--ORDER BY MAIN_MENU.RANKING
	;