
CREATE VIEW [APPLICATIONS].[V_APP_DATA_CONTROL] AS 
SELECT C.APP_ID, A.IS_ENABLED AS IS_APP_ENABLED, C.CONTROL_NAME, C.CONTROL_TYPE, C.CONTROL_LEVEL, C.CONTROL_VALUE, C.CONTROL_NOTE, C.IS_ENABLED AS IS_CONTROL_ENABLED, C.EDIT_BY, C.EDIT_DATE
FROM APPLICATIONS.TB_APP_DATA_CONTROL C
INNER JOIN APPLICATIONS.TB_APP A ON C.APP_ID = A.APP_ID;
