CREATE TABLE [INTERFACES].[TB_WEBSITE_MENU_ITEM] (
    [HEADER_ID]    VARCHAR (100) NOT NULL,
    [ITEM_NAME]    VARCHAR (100) NOT NULL,
    [DISPLAY_NAME] VARCHAR (100) NOT NULL,
    [ROUTE_TYPE]   VARCHAR (50)  NULL,
    [ROUTE]        VARCHAR (500) NOT NULL,
    [ICON]         VARCHAR (200) NOT NULL,
    [RANKING]      INT           NOT NULL,
    [IS_ENABLED]   CHAR (1)      NULL,
    [EDIT_BY]      VARCHAR (100) NOT NULL,
    [EDIT_TIME]    DATETIME      DEFAULT (getdate()) NOT NULL,
    PRIMARY KEY CLUSTERED ([HEADER_ID] ASC, [ITEM_NAME] ASC),
    CHECK ([IS_ENABLED]='N' OR [IS_ENABLED]='Y'),
    CHECK ([ROUTE_TYPE]='ASSET' OR [ROUTE_TYPE]='PAGE' OR [ROUTE_TYPE]='HTTP' OR [ROUTE_TYPE]='MENU'),
    FOREIGN KEY ([HEADER_ID]) REFERENCES [INTERFACES].[TB_WEBSITE_MENU_HEADER] ([HEADER_ID])
);





