CREATE TABLE [INTERFACES].[TB_WEBSITE_MENU_HEADER] (
    [HEADER_ID]        VARCHAR (100) DEFAULT ((format(getdate(),'yyyyMMddHHmmss')+'_')+CONVERT([nvarchar](50),newid())) NOT NULL,
    [SITE_ID]          VARCHAR (100) NOT NULL,
    [PARENT_HEADER_ID] VARCHAR (100) NULL,
    [USER_ID]          VARCHAR (100) NOT NULL,
    [MENU_NAME]        VARCHAR (100) NOT NULL,
    [DISPLAY_NAME]     VARCHAR (100) NOT NULL,
    [IS_ENABLED]       CHAR (1)      NULL,
    [EDIT_BY]          VARCHAR (100) NOT NULL,
    [EDIT_TIME]        DATETIME      DEFAULT (getdate()) NOT NULL,
    PRIMARY KEY CLUSTERED ([HEADER_ID] ASC),
    CHECK ([IS_ENABLED]='N' OR [IS_ENABLED]='Y'),
    FOREIGN KEY ([SITE_ID]) REFERENCES [NETWORK].[TB_WEBSITE] ([SITE_ID]),
    UNIQUE NONCLUSTERED ([HEADER_ID] ASC, [MENU_NAME] ASC)
);

