
CREATE VIEW PRODUCTS.V_SERVER_USAGE AS
WITH SERV AS (SELECT * FROM PRODUCTS.TB_SERVER WHERE STATUS <> 'REMOVED' OR LAST_SERVICE_DATE > DATEADD(MONTH, -6, GETDATE())),
	 HOST AS (SELECT * FROM NETWORK.TB_WEBSITE_HOST WHERE SERIAL_NO IN (SELECT SERIAL_NO FROM SERV)),
	 WEBS AS (SELECT * FROM NETWORK.TB_WEBSITE WHERE SITE_ID IN (SELECT SITE_ID FROM HOST))
SELECT S.SERIAL_NO, S.[STATUS] AS SERVER_STATUS, S.NET_LOAD_CAPACITY, S.SERVER_SPEC, S.CPU, S.RAM, S.STORAGE, S.REGISTRATION_DATE, S.LAST_SERVICE_DATE, S.OWNED_BY AS [SERVER_OWNED_BY], S.LOCATION_CODE,
		W.SITE_ID, W.APP_ID, W.DOMAIN_NAME, W.SITE_NAME, W.LOAD_BALANCING_ALGORITHM, W.IS_ENABLED AS [IS_SITE_ENABLED], W.OWNED_BY AS [SITE_OWNED_BY],
		H.HOST_IP, H.[PORT], H.[STATUS] AS HOST_STATUS, H.ERROR_MEASUREMENT_ALGORITHM, H.ERROR_RATE, H.MEASURED_TIME
FROM SERV S
LEFT JOIN HOST H ON S.SERIAL_NO = H.SERIAL_NO
LEFT JOIN WEBS W ON H.SITE_ID = W.SITE_ID;