
CREATE PROCEDURE APPLICATIONS.UPDATE_TASK_STATUSES
-- DECLARE
	@APP_ID VARCHAR(100),
	@PROGRAM_TYPE VARCHAR(50),
	@EDIT_BY VARCHAR(100)
AS
BEGIN

	-- SELECT * FROM APPLICATIONS.TB_PROGRAM_STATUS
	UPDATE APPLICATIONS.TB_PROGRAM_STATUS SET PROGRAM_STATUS = 'ERROR', NOTES = 'The task has stopped updating its status!', EDIT_BY = @EDIT_BY, EDIT_TIME = GETDATE()
	WHERE APP_ID = @APP_ID AND PROGRAM_TYPE = @PROGRAM_TYPE
	AND DATEDIFF(MINUTE, LAST_LOG_TIME, GETDATE()) > MAX_IDLE_INTERVAL;

END;