CREATE TABLE [EXTERNAL_STACKEXCHANGE].[TB_CS_EDUCATOR_RAW] (
    [ID]                  VARCHAR (100)  NOT NULL,
    [POST_TYPE_ID]        VARCHAR (100)  NOT NULL,
    [CREATION_DATE]       VARCHAR (50)   NOT NULL,
    [SCORE]               VARCHAR (10)   NOT NULL,
    [VIEW_COUNT]          VARCHAR (10)   NOT NULL,
    [BODY]                NVARCHAR (MAX) NOT NULL,
    [OWNER_USER_ID]       VARCHAR (100)  NOT NULL,
    [LAST_EDITOR_USER_ID] VARCHAR (100)  NOT NULL,
    [LAST_EDIT_DATE]      VARCHAR (50)   NOT NULL,
    [LAST_ACTIVITY_DATE]  VARCHAR (50)   NOT NULL,
    [TITLE]               NVARCHAR (500) NOT NULL,
    [TAGS]                NVARCHAR (500) NOT NULL,
    [ANSWER_COUNT]        VARCHAR (10)   NOT NULL,
    [COMMENT_COUNT]       VARCHAR (10)   NOT NULL,
    [CONTENT_LICENSE]     VARCHAR (50)   NOT NULL
);

