
CREATE FUNCTION [NETWORK].[GET_SERVER_DETAILS](@SITE_ID AS VARCHAR(100)) 
-- Created by Shu-Yuan Yang 10/18/2023
-- Query server details by website ID
-- Returns IP, IP status, server spec, storage, location, etc.
RETURNS TABLE AS RETURN
	WITH TB_H AS (SELECT * FROM NETWORK.TB_WEBSITE_HOST WHERE SITE_ID = @SITE_ID)
	SELECT TB_H.SITE_ID, S.SERIAL_NO, TB_H.HOST_IP, TB_H.PORT, S.STATUS AS SERVER_STATUS, TB_H.STATUS AS IP_STATUS, S.NET_LOAD_CAPACITY, S.SERVER_SPEC, S.STORAGE, S.REGISTRATION_DATE, S.LAST_SERVICE_DATE, S.LOCATION_CODE, S.RACK_CODE    
	FROM PRODUCTS.TB_SERVER S INNER JOIN TB_H ON S.SERIAL_NO = TB_H.SERIAL_NO
	WHERE S.STATUS <> 'REMOVED';
