

CREATE FUNCTION [NETWORK].[GET_SERVER_LOAD](@SITE_ID AS VARCHAR(100)) 
-- Created by Shu-Yuan Yang 09/20/2023
-- Query server load distribution by website ID
-- Returns IP, IP status, session count by IP, resource load by IP
RETURNS TABLE AS RETURN
	WITH TB_H AS (SELECT * FROM NETWORK.TB_WEBSITE_HOST WHERE SITE_ID = @SITE_ID), 
		TB_SER AS (
			SELECT S.SERIAL_NO, S.NET_LOAD_CAPACITY, S.STATUS AS SERVER_STATUS, TB_H.HOST_IP, TB_H.PORT, TB_H.SITE_ID, TB_H.STATUS AS IP_STATUS, 
				-- Shu-Yuan Yang 11/01/2023 added for more detailed server info
				S.SERVER_SPEC, S.STORAGE, S.REGISTRATION_DATE, S.LAST_SERVICE_DATE, S.LOCATION_CODE, S.RACK_CODE
			FROM PRODUCTS.TB_SERVER S INNER JOIN TB_H ON S.SERIAL_NO = TB_H.SERIAL_NO
		),
		TB_SESSION_DIST AS (
			SELECT TB_S.HOST_IP, COUNT(TB_S.SESSION_ID) AS SESSION_COUNT, SUM(RESOURCE_SIZE) AS RESOURCE_LOAD
			FROM NETWORK.TB_USER_SESSION TB_S 
			WHERE TB_S.HOST_IP IN (SELECT TB_H.HOST_IP FROM TB_H)
			GROUP BY TB_S.HOST_IP
		)
	SELECT TB_SER.SITE_ID, TB_SER.SERIAL_NO, TB_SER.HOST_IP, TB_SER.PORT, TB_SER.SERVER_STATUS, TB_SER.IP_STATUS, TB_SER.NET_LOAD_CAPACITY, ISNULL(DIST.SESSION_COUNT, 0) AS SESSION_COUNT, ISNULL(DIST.RESOURCE_LOAD, 0) AS RESOURCE_LOAD, 
		-- Shu-Yuan Yang 11/01/2023 added for more detailed server info
		TB_SER.SERVER_SPEC, TB_SER.STORAGE, TB_SER.REGISTRATION_DATE, TB_SER.LAST_SERVICE_DATE, TB_SER.LOCATION_CODE, TB_SER.RACK_CODE
	FROM TB_SER
	LEFT JOIN TB_SESSION_DIST DIST ON TB_SER.HOST_IP = DIST.HOST_IP
	;
