
CREATE FUNCTION NETWORK.IS_HOST_RESPONSIVE(@SERVER_STATUS AS VARCHAR(20), @IP_STATUS AS VARCHAR(20))
RETURNS CHAR(1)
AS
BEGIN
	DECLARE @YES CHAR(1) = 'Y', @NO CHAR(1) = 'N';
	IF @SERVER_STATUS IS NULL RETURN @NO;
	IF @IP_STATUS IS NULL RETURN @NO;

	IF @SERVER_STATUS NOT IN ('RUNNING') RETURN @NO;
	IF @IP_STATUS NOT IN ('NORMAL', 'ERROR') RETURN @NO;

	RETURN @YES;

END;