CREATE TABLE [NETWORK].[TB_HOST_STATUS_LOG] (
    [LOG_ID]         VARCHAR (150) NOT NULL,
    [HOST_IP]        VARCHAR (20)  NOT NULL,
    [HOST_STATUS]    VARCHAR (20)  NOT NULL,
    [TRACE_ID]       VARCHAR (100) NULL,
    [RECORD_TYPE]    VARCHAR (50)  NULL,
    [RECORD_MESSAGE] VARCHAR (500) NOT NULL,
    [ERROR_RATE]     FLOAT (53)    NOT NULL,
    [EDIT_BY]        VARCHAR (100) NOT NULL,
    [EDIT_TIME]      DATETIME      NOT NULL,
    [LATENCY] [float] DEFAULT (0) NOT NULL,
    PRIMARY KEY CLUSTERED ([LOG_ID] ASC),
    CHECK ([RECORD_TYPE]='NOTE' OR [RECORD_TYPE]='WARNING' OR [RECORD_TYPE]='ERROR' OR [RECORD_TYPE]='GOOD')
);


GO
CREATE NONCLUSTERED INDEX [HOST_STATUS_LOG_TIME_IDX]
    ON [NETWORK].[TB_HOST_STATUS_LOG]([HOST_IP] ASC, [EDIT_BY] DESC);

