CREATE TABLE [NETWORK].[TB_USER_SESSION_ITEM_HISTORY_LOG] (
    [SESSION_ID]       VARCHAR (100)  NOT NULL,
    [ITEM_NAME]        VARCHAR (250)  NOT NULL,
    [ITEM_DESCRIPTION] NVARCHAR (MAX) NOT NULL,
    [ITEM_SIZE]        INT            NOT NULL,
    [ITEM_ROUTE]       VARCHAR (500)  NOT NULL,
    [ITEM_POLICY]      VARCHAR (500)  NOT NULL,
    [EXPIRATION_TIME]  DATETIME       NULL,
    [DELETED_BY]       VARCHAR (100)  NOT NULL,
    [DELETED_TIME]     DATETIME       NOT NULL
);

