CREATE TABLE [NETWORK].[TB_USER_SESSION_HISTORY_LOG] (
    [SESSION_ID]        VARCHAR (100) NOT NULL,
    [CLIENT_IP]         VARCHAR (150) NOT NULL,
    [THREAD_ID]         VARCHAR (100) NOT NULL,
    [HOST_IP]           VARCHAR (20)  NOT NULL,
    [RESOURCE_UNIT]     INT           NOT NULL,
    [CLIENT_LOCATION]   VARCHAR (150) NOT NULL,
    [REQUESTED_TIME]    DATETIME      NOT NULL,
    [RESOURCE_SIZE]     INT           NOT NULL,
    [EDIT_BY]           VARCHAR (100) NOT NULL,
    [CONNECTED_TIME]    DATETIME      NOT NULL,
    [DISCONNECTED_TIME] DATETIME      NOT NULL,
    PRIMARY KEY CLUSTERED ([SESSION_ID] ASC)
);



