CREATE TABLE [NETWORK].[TB_USER_SESSION] (
    [SESSION_ID]      VARCHAR (100) DEFAULT ((format(getdate(),'yyyyMMddHHmmss')+'_')+CONVERT([nvarchar](50),newid())) NOT NULL,
    [CLIENT_IP]       VARCHAR (20)  NOT NULL,
    [THREAD_ID]       VARCHAR (100) NOT NULL,
    [HOST_IP]         VARCHAR (20)  NULL,
    [RESOURCE_UNIT]   INT           NOT NULL,
    [CLIENT_LOCATION] VARCHAR (150) NOT NULL,
    [REQUESTED_TIME]  DATETIME      NOT NULL,
    [RESOURCE_SIZE]   INT           NOT NULL,
    [EDIT_BY]         VARCHAR (100) NOT NULL,
    [EDIT_TIME]       DATETIME      NOT NULL,
    [IS_VALID]        CHAR (1)      NULL,
    PRIMARY KEY CLUSTERED ([SESSION_ID] ASC),
    CHECK ([IS_VALID]='N' OR [IS_VALID]='Y'),
    UNIQUE NONCLUSTERED ([CLIENT_IP] ASC, [THREAD_ID] ASC, [HOST_IP] ASC)
);



