CREATE TABLE [NETWORK].[TB_WEBSITE_HOST] (
    [HOST_IP]                     VARCHAR (20)  NOT NULL,
    [PORT]                        VARCHAR (10)  NOT NULL,
    [SITE_ID]                     VARCHAR (100) NULL,
    [SERIAL_NO]                   VARCHAR (50)  NULL,
    [STATUS]                      VARCHAR (20)  NULL,
    [EDIT_BY]                     VARCHAR (100) NOT NULL,
    [EDIT_TIME]                   DATETIME      NOT NULL,
    [ERROR_MEASUREMENT_ALGORITHM] VARCHAR (100) DEFAULT ('') NOT NULL,
    [ERROR_RATE]                  FLOAT (53)    DEFAULT ((0.0)) NOT NULL,
    [MEASURED_TIME]               DATETIME      DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_WEBSITE_HOST] PRIMARY KEY CLUSTERED ([HOST_IP] ASC, [PORT] ASC),
    CHECK ([STATUS]='ERROR' OR [STATUS]='DISABLED' OR [STATUS]='UNRESPONSIVE' OR [STATUS]='NORMAL'),
    FOREIGN KEY ([SERIAL_NO]) REFERENCES [PRODUCTS].[TB_SERVER] ([SERIAL_NO]),
    FOREIGN KEY ([SITE_ID]) REFERENCES [NETWORK].[TB_WEBSITE] ([SITE_ID])
);



