CREATE TABLE [APPLICATIONS].[TB_APP] (
    [APP_ID]          VARCHAR (100) NOT NULL,
    [APP_DESCRIPTION] VARCHAR (500) NOT NULL,
    [IS_ENABLED]      CHAR (1)      NULL,
    [OWNED_BY]        VARCHAR (50)  NOT NULL,
    [CREATED_BY]      VARCHAR (100) NOT NULL,
    [EDIT_BY]         VARCHAR (100) NOT NULL,
    [EDIT_DATE]       DATETIME      NOT NULL,
    PRIMARY KEY CLUSTERED ([APP_ID] ASC),
    CHECK ([IS_ENABLED]='N' OR [IS_ENABLED]='Y')
);

