CREATE TABLE [APPLICATIONS].[TB_CENTRAL_SYSTEM_LOG] (
    [LOG_ID]         VARCHAR (150) NOT NULL,
    [APP_ID]         VARCHAR (100) NOT NULL,
    [SYSTEM_NAME]    VARCHAR (100) NOT NULL,
    [TRACE_ID]       VARCHAR (100) NULL,
    [RECORD_TYPE]    VARCHAR (50)  NULL,
    [RECORD_KEY]     VARCHAR (150) NULL,
    [RECORD_VALUE1]  VARCHAR (250) NULL,
    [RECORD_VALUE2]  VARCHAR (250) NULL,
    [RECORD_VALUE3]  VARCHAR (250) NULL,
    [RECORD_VALUE4]  VARCHAR (250) NULL,
    [RECORD_VALUE5]  VARCHAR (250) NULL,
    [RECORD_MESSAGE] VARCHAR (500) NOT NULL,
    [RECORD_NOTE]    VARCHAR (500) NOT NULL,
    [EDIT_BY]        VARCHAR (100) NOT NULL,
    [EDIT_TIME]      DATETIME      NOT NULL,
    PRIMARY KEY CLUSTERED ([LOG_ID] ASC),
    CHECK ([RECORD_TYPE]='NOTE' OR [RECORD_TYPE]='WARNING' OR [RECORD_TYPE]='ERROR' OR [RECORD_TYPE]='GOOD'),
    FOREIGN KEY ([APP_ID]) REFERENCES [APPLICATIONS].[TB_APP] ([APP_ID])
);

